In [1]:
import numpy as np
a=np.array([1,2,3,4]) # array
a+1

array([2, 3, 4, 5])

In [2]:
#above is an scalar addition

In [3]:
a ** 2

array([ 1,  4,  9, 16])

In [4]:
# also it is an element wise operation. Each element is taken and processed accordingly

In [5]:
b=np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [6]:
a*b


array([2., 4., 6., 8.])

In [7]:
c=np.diag([1,2,3,4])
print(c*c)
prin(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


NameError: name 'prin' is not defined

In [8]:
c=np.diag([1,2,3,4])
print(c*c)
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [9]:
a=np.array([1,2,3,4])
b=np.array([2,3,2,4])
a==b

array([False, False, False,  True])

In [10]:
a>b

array([False, False,  True, False])

In [11]:
#To compare all the elements use the function array_equal() function

a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
np.array_equal(a,b)

True

In [12]:
c=np.array([1,1,1,4])
np.array_equal(a,c)

False

In [13]:
#Logical operations

a=np.array([1,1,1,0],dtype=bool)
b=np.array([1,1,0,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [14]:
np.logical_and(a,b)

array([ True,  True, False, False])

In [15]:
 #mathematical operations
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [16]:
np.log(a)

/home/prakash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [17]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [18]:
#shape mismatch

a=np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [19]:
#sum of array
a=np.array([1,2,3,4])
np.sum(a)

10

In [20]:
a=np.array([1,1],[2,2])
a

TypeError: data type not understood

In [21]:
a=np.array([[1,1],[2,2]])
a

array([[1, 1],
       [2, 2]])

In [22]:
a.sum(axis=0)

array([3, 3])

In [23]:
a.sum(axis=1)

array([2, 4])

In [24]:
#Other reductions

x=np.array([1,2,3,4])
x.min()

1

In [25]:
x.max()

4

In [26]:
x.argmin()

0

In [27]:
x.argmax()

3

In [28]:
np.all([True,true,True])

NameError: name 'true' is not defined

In [29]:
np.all([True,True])

True

In [30]:
np.any([True,true])

NameError: name 'true' is not defined

In [31]:
np.any([True,False])

True

In [32]:
a=np.zeroes((50,50))
np.any(a!=0)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [33]:
a=np.zeros((50,50))
np.any(a!=0)

False

In [34]:
np.all(a==a)

True

In [35]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b)&(b<=c)).np.all()

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [36]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b)&(b<=c)).all()

True

In [37]:
#statistics


In [42]:
x=np.array([1,2,3,1])
#y=np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [43]:
np.median(x)

1.5

In [44]:
np.median(y,axis=1)

array([2., 5.])

In [45]:
x.std()

0.82915619758885