In [1]:
#datatypes
import numpy as np
a=np.arange(10)
a.dtype

dtype('int64')

In [2]:
#explicit specifying of datatype we want
b=np.arange(10,dtype='float64')
b.dtype

dtype('float64')

In [3]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#default datatype is float for zeroes and ones function

In [6]:
c=np.zeros((3,3))
print(c)
c.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [7]:
d=np.array([1+2j,3+3j])
print(d.dtype)

complex128


In [9]:
e=np.array(['ram','rakash'])
e.dtype

dtype('<U6')

In [10]:
#slicing
f=np.diag([1,2,3])
print(f[2,2])

3


In [11]:
f[2,2]=5
f

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 5]])

In [13]:
#slicing
g=np.arange(10)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
g[1:8:2]

array([1, 3, 5, 7])

In [15]:
h=np.arange(10)
h[5:]=12
h

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12, 12])

In [17]:
#i=np.arange(10)
h[5:]=i[::-1]

ValueError: could not broadcast input array from shape (10) into shape (5)

In [19]:
i=np.arange(5)
h[5:]=i[::-1]
h

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [20]:
#copies and views

In [21]:
j=np.arange(10)
j

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
k=j[::2]

In [23]:
k

array([0, 2, 4, 6, 8])

In [24]:
np.shares_memory(j,k)

True

In [25]:
k[0]=10
k

array([10,  2,  4,  6,  8])

In [26]:
j

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [27]:
#j and k both points to the same memory location
#hence changing the value of k will change the value of j also

In [28]:
#To avoid that need to use copy() funciton in the assigning part

In [29]:
j=np.arange(10)
k=j[::2].copy()
k

array([0, 2, 4, 6, 8])

In [30]:
np.share_memory(j,k)

AttributeError: module 'numpy' has no attribute 'share_memory'

In [31]:
#typography mistake
np.shares_memory(j,k)

False

In [32]:
k[0]=0
k

array([0, 2, 4, 6, 8])

In [33]:
j

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
k[0]=111
k

array([111,   2,   4,   6,   8])

In [35]:
j

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#fancey indexing

In [41]:
l=np.random.randint(0,20,15)
l

array([ 5,  8,  2, 17, 11,  7, 15,  0, 16, 12, 14, 12,  0,  0,  8])

In [38]:
mask=(a%2 ==0)

In [42]:
extract = l[mask]
extract

IndexError: boolean index did not match indexed array along dimension 0; dimension is 15 but corresponding boolean dimension is 10