In [1]:
#extension package for using multi dimensional array
#better on hardware(efficiency)
#best for scientific operation
#also called array oriented computation


In [2]:
import numy as np
a = np.array([0,1,2,3])
print(a)

print(np.arange(10))

ModuleNotFoundError: No module named 'numy'

In [3]:
import numpy as np
a = np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Comparison between list and numpy

l=range(1000)
%timeit [i ** 2 for i in l]

392 µs ± 1.36 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
#numpy implementaion

a = np.arange(1000)
%timeit a**2

3.58 µs ± 86.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
#how to contruct a numpy array

b=np.array([0,1,2,3])
b

array([0, 1, 2, 3])

In [10]:
b.ndim

1

In [11]:
b.shape

(4,)

In [12]:
len(b)

4

In [13]:
#two dimensional array
c=np.array([[0,1,2],[2,3,4]])
c

array([[0, 1, 2],
       [2, 3, 4]])

In [14]:
c.ndim

2

In [15]:
c.shape

(2, 3)

In [17]:
len(c) #will give the size of first dimension or row

2

In [20]:
#three dimensional array
d=np.array([[0,1],[2,3],[3,4]])
d

array([[0, 1],
       [2, 3],
       [3, 4]])

In [21]:
d.ndim

2

In [22]:
#3dimensional array should have 4 elements #image the 3 dimensional box

In [27]:
e=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
e

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [28]:
e.ndim

3

In [29]:
e.shape

(2, 2, 2)

In [30]:
#1 d array - vector
#2 d array - matrix
#n d array - tensor (n can be anything)