In [1]:
#FUNCTIONS FOR CREATING ARRAYS

In [2]:
#using arange function
#arange is an array valued version of built in python range function

In [4]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#start, end, step
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [6]:
#using linspace
#start, end, numeber of points
c=np.linspace(0,1,6)
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [8]:
#In linspace we use number of points not number of steps
#depend on users need it will automatically allocate step

In [10]:
#common array
d=np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
e=np.zeroes((3,3))

AttributeError: module 'numpy' has no attribute 'zeroes'

In [12]:
#it should not include e in zero
e=np.zeros((3,3))
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:

f=np.eye(3,2)
f

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [16]:
g=np.diag([1,2,3,4])
g

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
np.diag(g)

array([1, 2, 3, 4])

In [18]:
#create array using random
h=np.random.rand(4)  
h

array([0.63231578, 0.94015564, 0.14577318, 0.46681918])

In [20]:
i=np.random.randn(4)
i

array([-0.4954126 , -0.85682931,  0.08860391, -1.29948416])

In [ ]:
#rand - will print unifrom distributed random number
#randn - gaussian distributed random number / standard normal 